config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :itineraries, :visits

  root 'itineraries#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    has_many :visits
end

app/models/visit.rb
class Visit < ApplicationRecord
    belongs_to :itinerary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
    def create
        @itinerary = Itinerary.new(itinerary_params)
        @itinerary.save
        redirect_to @itinerary
    end

    def new
        
    end

    def show
        @itinerary = Itinerary.find(params[:id])
        @visits = @itinerary.visits.all
    end

    private
        def itinerary_params
            params.require(:itinerary).permit(:name, :start, :end)
        end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
    wrap_parameters format: [:json, :xml]

    def create
        @itinerary = Itinerary.find(params[:visit][:itinerary_id])
        @visit = Visit.new(visit_params)
        @visit.save
    end

    private
        def visit_params
            params.require(:visit).permit(:name, :latitude, :longitude, :rating, :day, :start, :end, :itinerary_id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/itineraries/new.html.erb
<%= image_tag('background-image.png', style: "height: 100%; width: 100%") %>
<h4>
<div class = "vert" style="padding: 10px; background: rgba(76, 175, 80, 0.3);"> 
    <div class = "center"> 
            <%= form_with scope: :itinerary, url: itineraries_path, html: {class: "form-horizontal justify-content-center"}, local: true do |form| %>
            <%= form.text_field :name, placeholder: 'Trip Name', required: true %>
            <label for="start">Start Date</label>
            <%= form.date_field :start, required: true %>
            <label for="start">End Date</label>
            <%= form.date_field :end, required: true%>
            <%= form.submit "Make Itinerary", {class: "btn btn-success"} %>
        <% end %>
    <div/>
<div/>

app/views/itineraries/show.html.erb
<div class="container">
    <%= react_component('LandmarksComponent', {
        id: @itinerary.id,
        start: @itinerary.start,
        end: @itinerary.end,
        visits:@itinerary.visits,
    }, id: "landmarks", class: "panel") %>
    <%= react_component('ItineraryComponent', {
        id: @itinerary.id,
        name: @itinerary.name,
        start: @itinerary.start,
        end: @itinerary.end,
        visits: @itinerary.visits,
    }, id: "itinerary", class: "panel") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google[:api_key] %>&libraries=places" type="text/javascript"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>